---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categorias":
    get:
      summary: Listar Categorias
      parameters:
      - name: page
        in: query
        description: Número da página
        schema:
          type: integer
      - name: per_page
        in: query
        description: Número de itens por página
        schema:
          type: integer
      tags:
      - Categorias
      responses:
        '200':
          description: categorias encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/categoria"
    post:
      summary: Criar Categoria
      tags:
      - Categorias
      parameters: []
      responses:
        '201':
          description: categoria criada
        '422':
          description: categoria não criada
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                slug:
                  type: string
              required:
              - nome
              - slug
  "/categorias/{slug}":
    get:
      summary: Exibir uma Categoria
      tags:
      - Categorias
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: categoria encontrada
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/categoria"
        '404':
          description: categoria não encontrada
    put:
      summary: Atualizar uma Categoria
      tags:
      - Categorias
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: categoria atualizada
        '404':
          description: categoria não encontrada
        '422':
          description: categoria não atualizada
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                slug:
                  type: string
              required:
              - nome
              - slug
  "/produtos":
    get:
      summary: Listar Produtos
      parameters:
      - name: page
        in: query
        description: Número da página
        schema:
          type: integer
      - name: per_page
        in: query
        description: Número de itens por página
        schema:
          type: integer
      tags:
      - Produtos
      responses:
        '200':
          description: produtos encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/produto"
    post:
      summary: Criar Produto
      tags:
      - Produtos
      parameters: []
      responses:
        '201':
          description: produto criado
        '422':
          description: produto não criado
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/produto"
  "/produtos/{slug}":
    get:
      summary: Busca um Produto pelo seu Slug
      tags:
      - Produtos
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: produto encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/produto"
        '404':
          description: produto não encontrado
    put:
      summary: Atualizar Produto
      tags:
      - Produtos
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: produto atualizado
        '404':
          description: produto não encontrado
        '422':
          description: produto não atualizado
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/produto"
  "/produtos/nome/{nome}":
    get:
      summary: Busca Produtos por nome
      tags:
      - Produtos
      parameters:
      - name: nome
        in: path
        description: Nome do produto
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Produtos encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/produto"
        '404':
          description: Nenhum produto encontrado
components:
  schemas:
    produto:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        slug:
          type: string
        descricao:
          type: string
        preco:
          type: number
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - nome
      - descricao
      - preco
    categoria:
      type: object
      properties:
        slug:
          type: string
        nome:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - nome
      - descricao
