source "https://rubygems.org"

ruby "3.3.2"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "puma", ">= 5.0"
gem "pg", "~> 1.2"
gem "active_model_serializers", "~> 0.10.0"
gem "kaminari"
gem "rack-cors"
gem "bcrypt", "~> 3.1", ">= 3.1.11"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "factory_bot_rails"
  gem "faker"
  gem "simplecov", require: false
  gem "cucumber-rails", require: false
  gem 'database_cleaner', '~> 2.0', '>= 2.0.2'
end

group :test do
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end

gem 'rswag'
gem 'rswag-api'
gem 'rswag-ui'
